### PR TITLE
add eval page to site header

### PR DESCRIPTION
**Pull request by sdtaylor**
#114

### CODE REVIEW

**Comment by ethanwhite** [comment]
Looks like the build is failing now.

**Comment by sdtaylor** [comment]
this error is bigger than this commit. #116

**Comment by sdtaylor** [comment]
@ethanwhite can you start the build again? This PR in PortalData has hopefully fixed things, https://github.com/weecology/PortalData/pull/134

**Comment by gmyenni** [comment]
Restarted

**Pull request merged**
