### PR TITLE
Modify figures to address #170 and #171

### PR DESCRIPTION
**Pull request by gmyenni**

### CODE REVIEW

**Comment by gmyenni** [comment]
Okay, that version is up. Does it seem a little redundant now?
Would it be possible to just do all this in the figure caption?
"Box colors correspond to colors and stages in Figure 1. Travis CI and Github logos are used to indicate where that software is employed."
Also, I kind of liked how using the actual name of the repos in the boxes points people to our repos.

This version seems to do the job of both the old figures 1 and 2, like we talked about combining them in #155 .

**Comment by ha0ye** [comment]
Some thoughts:
1. Would using a bulleted list help with the current comma-separated tasks that Travis CI takes care of?
2. Maybe an additional icon for "human scientists". This could then be referenced in the paper in discussion of human involvement only where necessary, so as to reduce bottlenecks in scientific progress.
3. The different shapes are a bit distracting for me. Could they be made meaningful? e.g. archiving looks like a file drawer, presentation looks like a website, repos are stacked disk cylinders, data entry looks like a gridded lab notebook, R package is a hex sticker (https://github.com/weecology/portalr/issues/78)?
4. For consistency, can the arrows to "Archiving" and "Presentation" terminate at the sides of the icons instead of top and bottom?

**Comment by gmyenni** [comment]
figure2

Version incorporating Hao's suggestions

**Comment by gmyenni** [comment]
figure2simple

Version incorporating some suggestions, with simplified shapes

**Comment by gmyenni** [comment]
Post-discussion figure
portalforecastingfigure1

If you want to improve the spatial organization or try out other changes, you can find the figures here:
https://docs.google.com/presentation/d/1lA9je4gTW6NzTBRg0XBIqJw_4GtxB-w50hUXO0Cf57Q/edit?usp=sharing

**Comment by emchristensen** [comment]
Is it confusing that there are two types of arrows?  Arrows pointing back at the same box are different than arrows between boxes.  I feel like they should all look the same.

**Comment by gmyenni** [comment]
> Is it confusing that there are two types of arrows? Arrows pointing back at the same box are different than arrows between boxes. I feel like they should all look the same.

The two types of arrows do mean different things; tasks that happen within a repo vs the progression between stages. Is that more confusing than helpful? Maybe that's a distinction that doesn't need to be made.

**Comment by juniperlsimonis** [comment]
from looking at recent articles in MEE, there's actually a much wider flexibility in size than what's in the Wiley figure guidelines they cite. 
for example: http://onlinelibrary.wiley.com/doi/10.1111/2041-210X.12967/full

**Comment by juniperlsimonis** [comment]
Played around with combining things into a single, multi-part figure
clipboard01

**Comment by ha0ye** [comment]
Vertical Orientation going with two panels (A, left side) overview and (B, right side) infrastructure and automation.
portalforecastingfigure1 vertical hy

**Comment by ethanwhite** [comment]
Nice iteration everyone. I really like the resulting vertical version. Let's update to it in this PR and then I'll get it merged.

**Comment by bleds22e** [comment]
I'm not 100% sold on "logbooks" and the keyboard with black background (is there somewhat to get a keyboard without a background that still shows up?), but otherwise, I really like the vertical version as well!

**Comment by sdtaylor** [comment]
Agreed, the vertical version fixes several issues we had with having them separate.

**Comment by ha0ye** [comment]
@bleds22e It's a new slide in the google slides link @gmyenni posted earlier. "logbooks" is something I added, so it's more for lack of imagination on my part than anything else.

I don't know about the black background for the keyboard, something with the rendering to PNG must have dropped transparency? (It does look fine in Google slides.)

**Comment by gmyenni** [comment]
Would it make sense for the first box to say 'field site' instead of logbooks? I mean, data collection happens in the field, like data sharing happens in the portal data repo, etc.

**Comment by ethanwhite** [comment]
> Would it make sense for the first box to say 'field site' instead of logbooks? I mean, data collection happens in the field, like data sharing happens in the portal data repo, etc.

I could see that or something "data sheets" or "researcher's computer"

Also, since we're talking details, I don't think I like "develop models" and the person icon at the "modeling and forecasting" step. Yes, we do need humans to develop models, but that's not what's happening in the infrastructure. I think we should drop the keyboard and replace "develop models" with "fit models" and "make forecasts" and "evaluate forecasts".

**Comment by ethanwhite** [comment]
At that point I think we can also just drop the "Human Tasks" icon since it would only occur once and is pretty self-evident for that step.

**Comment by gmyenni** [comment]
Thanks everyone. I think this is looking great! Latest version is in the PR. I also got a better screenshot of the website, now that the alignment issue is fixed. Anything else?

**Comment by ethanwhite** [comment]
LGTM. Great work figuring out this figure everyone!

**Pull request merged**
