### PR TITLE
Juniper edits and comments on the ms

### PR DESCRIPTION
**Pull request by juniperlsimonis**

### CODE REVIEW

**Comment by ethanwhite** [comment]
Note, this PR shouldn't be merged.

**Comment by juniperlsimonis** [comment]
Was this an ok way to share the edits in the repo or should I have done it a different way?

**Comment by ethanwhite** [comment]
@DAPPERstats - yep, this is totally fine. I just didn't want to clutter up the repo with a friendly review and wasn't sure if someone else might merge the PR without thinking about it. In the future an issue with a file attached containing the review might be a slightly better version of this since it accomplishes the same thing without the risk of the merge.

**Comment by juniperlsimonis** [comment]
ok, phew. Roger that re: issue with an attachment. That totally makes sense.

**Comment by ethanwhite** [comment]
Closed by #189.

**Pull request closed without merging**
