### PR TITLE
Interpolate nbgarch

### PR DESCRIPTION
**Pull request by juniperlsimonis**
this is the update of the negative binomial tsglm model, now nbgarch (negative binomial GARCH: generalized autoregressive conditional heteroskedasticity)

it replaces the neg_binom_ts.R script with the nbgarch.R script

### CODE REVIEW

**Comment by juniperlsimonis** [comment]
Also, just to document it here, I caught an issue with the AIC calculations. In some situations, the summary function doesn't work with the fitted model object (I'm not quite sure why, but it likely has something to do with a variance covariance matrix, because the error thrown is about a decomposition function) and so the tryCatch spits out an AIC of 1e6, but the model object actually has a log likelihood value and works within the AIC function to produce a sensible value. 

So, I don't know what the issue is, but suffice it to say that if you were to re-run historical analyses, you'd be not only changing the interpolation and such here, but there's also a change in the collection of AIC values.

**Comment by juniperlsimonis** [comment]
incorporated updates similar to those in #196 and #197

**Comment by juniperlsimonis** [comment]
note to self: ok, so something with the species part is what's causing the break.

**Comment by juniperlsimonis** [comment]
it looks like the removal of PI addressed whatever the issue was here with the output breaking travis.
so, this model is now passes checks and is ready to be looked at!

**Review by ethanwhite — APPROVED** [review]
LGTM. Nice work!

**Pull request merged**
