### PR TITLE
Refactor simple models to be called from PortalForecasts.R

### PR DESCRIPTION
**Pull request by gmyenni**
This seems to be working. I created all the 2017-04-26 files from it, in the predictions folder.

### CODE REVIEW

**Review by ethanwhite — COMMENTED** [review]
This is erroring for me locally at the moment because it's looking for the model functions in the home directory. The paths should be set to the working directory, e.g.,

`source('models/naive01.R')`

**Comment by ethanwhite** [comment]
`abundance-gam` also failed for me:

```
Error in source("models/abundance-gam.R") : 
  models/abundance-gam.R:112:9: unexpected '='
111: 
112: if(level=
```

**Comment by ethanwhite** [comment]
Looks really good overall. I tested this against `master` and it gives the same results (within the limits of parameter convergence differences) and this is definitely a nice step forward in readability and understandability. If you can fix the path issue and either fix `abundance-gam` or take it back out for the moment I think this will be in good shape.

My one other thought is that we should just remove the plotting code in `abundance-gam` unless either you or @davharris think it's important to keep it. It will always be there in the history if we need to go get it again and it's generally good code hygiene to delete code that is being used rather than commenting it out.

**Comment by davharris** [comment]
I vote to kill the gam code; I wrote it before I understood splines (I still don't actually understand them).

Unless its predictions are especially good, in which case I can revise the code. But otherwise, feel free to delete it all. 

Dave

**Comment by ethanwhite** [comment]
OK, I did something a little advanced this morning, which is that rebased my changes against your PR and then submitted a PR to your branch. What this means is that you should have a PR against your repo. If you merge it those changes will show up in this PR. The changes I made take care of the two issues I mentioned above and implement the refactoring in the data oriented code that we'd discussed.

I tested this code against `master` and it looks like we're getting the same results minus small differences due to convergence issues.

**Comment by gmyenni** [comment]
Awesome! Thanks.

**Comment by ethanwhite** [comment]
OK, given the absence of any objections I'm going to go ahead and merge this.

@davharris - we've back to not running the GAM, but it hasn't been removed yet. Feel free to PR in it's removal.

**Pull request merged**
