### PR TITLE
Improvements to weekly forecast script

### PR DESCRIPTION
**Pull request by ethanwhite**
* More descriptive logging
* Instead of deleting singularity container force replace if updated
* Instead of deleting forecasts repo update it

### CODE REVIEW

**Review by henrykironde — APPROVED** [review]
All LGTM

**Comment by ethanwhite** [comment]
Thanks @henrykironde! Go ahead and merge when ready.

**Comment by henrykironde** [comment]
Sorry for the delayed merge, I was expecting another set of eyes.

**Comment by ethanwhite** [comment]
No problem. I was updating the name of the main branch this morning and wanted to merge all the PRs first. In general I think one review is enough unless we specifically think multiple folks should look at it, in which case let's add them explicitly as reviewers to help everyone keep track of what we want them to look at.

**Pull request merged**
