### PR TITLE
added title argument to plot_species_forecast(); added plot of just c…

### PR DESCRIPTION
**Pull request by emchristensen**
…ontrol plots to Rodent Report page on website

### CODE REVIEW

**Comment by gmyenni** [comment]
If this is ready, can you render site, so the images update?

**Comment by emchristensen** [comment]
can I what now?

**Comment by ethanwhite** [comment]
Looks like maybe we missed one change with the observed values still being for the full site. At least they are substantial under predictions otherwise.

**Comment by emchristensen** [comment]
I believe the observed values should be correct-- I did a filter(treatment=='control') in line 12.  The predictions for controls are just not good.

**Comment by ethanwhite** [comment]
Ah, OK, thanks. I was just really surprised that the models do so much worse on the controls.

**Comment by emchristensen** [comment]
Also, some terrible things happened to my files when I did a site render. It took me half an hour to get rid of conflicts and now it looks like I reverted everyone else's changes from the last 24 hours. I'm tempted to delete my repo and start over.

**Comment by gmyenni** [comment]
If you can get this back on track. . . can you switch to using only the longterm controls in `report.Rmd`?

**Pull request closed without merging**
