### PR TITLE
fixing get_future_moons function

### PR DESCRIPTION
**Pull request by emchristensen**
fixed function so it can deal with transition from december to january.  this should fix issue #162

### CODE REVIEW

**Comment by ethanwhite** [comment]
This is an improvement, so I'm going to go ahead and merge it, but it appears to trigger a new set of problems with overlapping error bars in the species level forecasts.

screenshot from 2018-01-26 08-26-10

**Comment by emchristensen** [comment]
I'm not seeing the same problem when I run the code locally, but it also still says Jan 2017 -- do I need to rebuild something?

**Comment by ethanwhite** [comment]
Interesting, I got this from building locally inside the docker container. The next cron job should run in the next 30 minutes. Let's see what the site looks like then and if it does we can figure out what's going on.

**Comment by emchristensen** [comment]
It just occurred to me that the plotting function relies on the 'forecastmonth' and 'forecastyear' columns from the csvs, which will still be wrong even though I fixed the function that creates them (unless we go in and modify the csvs for past predictions). I just changed the plotting function so it finds dates directly from the newmoonnumber and ignores those columns (which I probably should have done in the first place), should I push that change up now or should we see what happens with the cron job first?

**Comment by ethanwhite** [comment]
The cron job is currently running. If you've fixed something go ahead and submit a new PR.

**Pull request merged**
