### PR TITLE
Add most recent errors

### PR DESCRIPTION
**Pull request by sdtaylor**
Adding a figure to the eval page which graphs the error of the  most recent samples.

#144

### CODE REVIEW

**Comment by sdtaylor** [comment]
Here is how this renders on the finished page.


image

**Review by ethanwhite — COMMENTED** [review]
This looks awesome @sdtaylor! I've made a couple of minor cleanup suggestions in-line, but otherwise I think this is good to go.

**Comment by sdtaylor** [comment]
@ethanwhite I made the changes you suggested.

**Comment by ethanwhite** [comment]
Perfect. Nice work @sdtaylor!

**Pull request merged**
