### PR TITLE
Update hindcasting

### PR DESCRIPTION
**Pull request by sdtaylor**

### CODE REVIEW

**Comment by sdtaylor** [comment]
this is running and looks to be working good. will update with the new hindcast files soon

**Comment by ethanwhite** [comment]
Awesome. Can you also squash the commits when you update?

**Comment by sdtaylor** [comment]
this is ready to go. i'm not sure how to squash everything outside a merge squash

**Comment by ethanwhite** [comment]
Turns out the merge makes things complicated so I'm just going to go ahead and merge this as is.

**Pull request merged**
