### PR TITLE
[WIP] Load newest Portal Data before forecasting

### PR DESCRIPTION
**Pull request by ethanwhite**

### CODE REVIEW

**Comment by sdtaylor** [comment]
fyi this will break hindcasting the way it's currently setup.

**Comment by sdtaylor** [comment]
`do_hindcasts.R` sets up a post dated PortalData folder then calls `PortalForecasts.R`. If `PortalForecasts.R` downloads the newest data fresh again then it will just keep forecasting from the most recent sample date.

**Comment by ethanwhite** [comment]
Oh right. Thanks for the reminder! We definitely need to refactor that code. I've added a `[WIP]` here. Let's not merge this for the moment while we figure out that larger situation.

I'm poking around this codebase this afternoon (can't get my brain to write the things it's supposed to) trying to understand the state of everything so hopefully I'll be better able to engage in discussions of refactoring the repo soon.

**Comment by gmyenni** [comment]
Was this sorted in https://github.com/weecology/portalPredictions/pull/69 ?

**Comment by ethanwhite** [comment]
It shouldn't have been since that would break `do_hindcasts.R` until we finish revising how it works.

**Comment by ethanwhite** [comment]
Implemented in 4e544f6e2d159e9066e4de8eba23ef6d6b75952d.

**Pull request closed without merging**
