### PR TITLE
Interpolate weecology arima

### PR DESCRIPTION
**Pull request by juniperlsimonis**
this PR adds a new model script for "weecology-arima", the provisional more specific name of "naive02", which also includes interpolation for missing data.
this model is not directly comparable to the four existing models as the data set is augmented to account for the missing values

### CODE REVIEW

**Review by ethanwhite — CHANGES_REQUESTED** [review]
See review of #196 and apply the same ideas here.

**Comment by gmyenni** [comment]
I also added comments for both over in #196

**Comment by juniperlsimonis** [comment]
checks have passed here! ready for an evaluation for merging.

**Comment by gmyenni** [comment]
To match the existing name, it should be 'AutoArima'.

**Comment by juniperlsimonis** [comment]
name's been updated and the edits from esss have been pulled over into here as well

**Comment by juniperlsimonis** [comment]
i've made all the changes you requested in #196 here as well @ethanwhite and updated the name as you requested, @gmyenni 
i also updated the data input file to include the removal of PI (i.e., i ported in the updated script and data from #211) to make sure there weren't any problems being introduced by that

everything has passed checks, so it should be good, unless y'all notice anything else

**Review by ethanwhite — APPROVED** [review]

**Comment by ethanwhite** [comment]
:+1:

**Pull request merged**
