### PR TITLE
Correctly state that prediction intervals are 90% in evaluation

### PR DESCRIPTION
**Pull request by ethanwhite**
The prediction intervals have always been 90%, but they were described and shown
as 95%. This fixes this issue and in the process creates a new metadata value
for the prediction interval (thanks to @ha0ye's suggestion) that can be used
throughout the code base. Updates to the models will be necessary to use this
value for all instances of prediction interval in the code base.

### CODE REVIEW

**Comment by ethanwhite** [comment]
Hmmm. All I can think of is that maybe in some versions of `knitr` variables aren't shared between blocks in the same way. Attempted fix based on that hypothesis inbound.

**Comment by ethanwhite** [comment]
I don’t know why using the variable was causing this to fail, but this works and we can improve on it later.

**Review by juniperlsimonis — APPROVED** [review]
weird!
but yeah, that seems like something to track down later.
nice that it at least works for the markdown text like it should

**Comment by ethanwhite** [comment]
My current guess is that it's a type issue where different versions of the `yaml` package are reading in that number as different types (e.g., as a string). But I'm going to control myself and leave that to run down later.

**Pull request merged**
