### PR TITLE
download and check status of observed rodent data

### PR DESCRIPTION
**Pull request by sdtaylor**
To do
download weather data

### CODE REVIEW

**Comment by sdtaylor** [comment]
This is ready to be checked. There is path stuff in here so it should be tested on windows and mac. Also note that it will delete everything inside your PortalData folder and replace it with the the current PortalData github repo. If you're storing any custom or modified files in PortalData you should put them somewhere else.

**Comment by ethanwhite** [comment]
I'm happy to merge this as is since it looks like it should do the job. That said, if I understand everything correctly we're just getting a single data file, the main rodents table from `master`, in which case it would probably be simpler to access that file directly at https://raw.githubusercontent.com/weecology/PortalData/master/Rodents/Portal_rodent.csv instead dealing with the zip and associated renaming.

**Comment by sdtaylor** [comment]
Other data that models might use need to be downloaded too. Such as the moon_dates, precipitation, plants, etc, so grabbing the zip is easier. The check function just uses `Portal_rodent.csv` as it consistently signals a new update.

**Comment by ethanwhite** [comment]
Ah got it. Thanks. In it goes!

**Pull request merged**
