### PR TITLE
Remove testit library

### PR DESCRIPTION
**Pull request by gmyenni**
Use tryCatch to test for model aic errors.
Also moved abundance-gam to developing models.

### CODE REVIEW

**Comment by sdtaylor** [comment]
I think the tryCatch lines can be simplified to this

```
proposed_model_aic = tryCatch(summary(proposed_model)$AIC,
                                error = function(x){1e6})
```

**Comment by gmyenni** [comment]
Okay, that works.

**Comment by sdtaylor** [comment]
Runs great.

**Comment by sdtaylor** [comment]
#74

**Pull request merged**
