### PR TITLE
Fix pev garch and nb garch hindcast

### PR DESCRIPTION
**Pull request by juniperlsimonis**
edited model scripts to handle misbehaving models
edited hindcast script to use lagged weather with pevgarch
reran hindcasts

### CODE REVIEW

**Review by ethanwhite — CHANGES_REQUESTED** [review]
Thanks @DAPPERstats. Most of this looks great. A couple of things to deal with:

1. Given that this is for hindcasts I don't think we should update `model_metadata.yaml`, `rodent_all.csv`, `rodent_controls.csv`, or `weather_data.csv`. We're effectively setting these to arbitrary values to run the hindcasts so storing them will make the history of those files confusing.

2. The rewrite of pevGARCH is a difficult for me to follow due to the large numbers of `tryCatch` and `is.na` checks. If I'm reading this right we fit all the models, catching each fit if it errors, if the best model still failed then we set the results to `zero_abund_forecast`, we then predict, we catch errors from prediction, if there was a prediction error then we refit the model again without environmental predictors (which we've done before, but now we're falling back to?), catching errors in that fit, and predict again (this time not checking for errors from prediction, which I'm not sure I understand) and use that model (but without updating the AIC value (which I don't understand yet), if that prediction is NA then we fall back to `zero_abund_forecast`. Is that right? If that's the idea then this needs to be heavily documented or the code needs to be clarified.

I'm wondering if it might be possible to simplify this by doing the prediction step for all models as they are fit. The logic would then be something like: 1. fit model (catching errors), 2. predict from model (catching errors), 3. check if model & prediction worked and the fit is better than the current best model, 4. if so update the best model, 5. if best model is never updated fall back to `zero_abund_forecast`.

**Comment by juniperlsimonis** [comment]
For sure!

1. Totally. Those just get updated automatically with the hindcasting. I just pushed a commit that reverted those files to what they are in the master.

2. Yeah, I had to patch a few things as I was going along, so that could definitely be confusing and is almost certainly doubling checking up where it doesn't need to be. What you propose totally makes sense, and should work. I'll get to this in a bit do need to make sure I have everything set up right with the error checking when it runs and then push a commit with just that file edited.

**Comment by juniperlsimonis** [comment]
Just pushed the updated pevGARCH script commit that has that edit integrated.
I did some spot checks with the updated script and it looks like it works fine for forecasts and hindcasts.

**Review by ethanwhite — APPROVED** [review]

**Comment by ethanwhite** [comment]
Thanks! Much more readable now!

**Pull request merged**
