### PR TITLE
incorporate individual model variance into ensemble variance

### PR DESCRIPTION
**Pull request by sdtaylor**
@davharris is this correct?

### CODE REVIEW

**Comment by davharris** [comment]
I think so, depending on whether you want to use sample variance or population variance in the second term (which corresponds to using `N` or `N-1` in the denominator when calculating the variance).

I'd lean toward sample variance (i.e. toward using the correction factor). [Wikipedia says there are two ways to do this for weighted samples](https://en.wikipedia.org/wiki/Weighted_arithmetic_mean#Weighted_sample_variance). The "reliability weights" seem more appropriate here, I think. This is the equation I'd recommend using:

image

**Comment by davharris** [comment]
Oh, also: V1 is the sum of the weights (probably 1 in our case?) and V2 is the sum of squared weights.

**Comment by sdtaylor** [comment]
So like this?
```
  weighted_estimates = all_forecasts %>%
    mutate(model_var = ((UpperPI - estimate)/CI_quantile)^2) %>%
    left_join(weights, by=c('date','model','currency','level','species')) %>%
    group_by(date, NewMoonNumber, forecastmonth, forecastyear,level, currency, species) %>%
    summarise(ensemble_estimate = sum(estimate*weight), 
              ensemble_var   = sum(model_var * weight) + (sum((weight*(estimate - ensemble_estimate))^2) / (sum(weight) - (sum(weight^2)/sum(weight)))  ) %>%
    ungroup()
```

**Comment by sdtaylor** [comment]
hold  up. i'm getting a lot of infinite values with that.

**Comment by sdtaylor** [comment]
hmm, there is problem since some of our weights are dominated by a single model, the denominator in that equation rounds out to 0.

**Comment by davharris** [comment]
oh, right. Let's use the other weighting equation, then.

**Comment by sdtaylor** [comment]
so how it is currently in the PR?

**Comment by davharris** [comment]
No, I meant the "frequency weights" from the page I linked.

image

**Comment by sdtaylor** [comment]
That will also have a denominator of 0 if V1 is still the sum of the weights.

**Comment by davharris** [comment]
Excellent point. I think the denominator should be N * V1 - 1, but I'll look for a source.

**Comment by davharris** [comment]
[Confirmed](https://stats.stackexchange.com/a/61298/4862) 

>Important Note: this works only if the weights are "repeat"-type weights, meaning that each weight represent the number of occurrences of one observation, and that $\sum_{i=1}^N w_i=N^*$ where $N^*$ represent the real sample size (real total number of samples, accounting for the weights).

**Comment by davharris** [comment]
(assuming that your V1 equals 1)

**Comment by sdtaylor** [comment]
Cool. Here's a sample of some ensembles produced. They look good to me 


image

**Comment by davharris** [comment]
I think there's a misplaced parenthesis and the weights are getting squared.  This would be clearer:

```
diff = estimate - ensemble_estimate
sum(weight*diff^2) / (n() - 1)
```

**Comment by sdtaylor** [comment]
I can't do that because equations in `group_by` must give a single value. How about this?

```  
weighted_estimates = all_forecasts %>%
    mutate(model_var = ((UpperPI - estimate)/CI_quantile)^2) %>%
    left_join(weights, by=c('date','model','currency','level','species')) %>%
    group_by(date, NewMoonNumber, forecastmonth, forecastyear,level, currency, species) %>%
    summarise(ensemble_estimate = sum(estimate*weight), 
              weighted_sum_of_squares = sum(weight * (estimate - ensemble_estimate)^2) ,
              ensemble_var   = sum(model_var * weight) + sum_of_squares / (n()*sum(weight)-1)) %>%
    ungroup()
```

**Comment by davharris** [comment]
Better.

* I think `sum_of_squares` might be renamed to clarify that it's weighted (maybe "weighted_sum_of_squares" or "weighted_ss").
* The code now assumes that sum(weight)==1, so it would be good to add an assertion about this if we don't already have one.

**Comment by sdtaylor** [comment]
Ok, that should do it.

**Comment by ethanwhite** [comment]
Nice! Will leave this for @davharris to merge once he's checked the final changes.

**Comment by davharris** [comment]
Looks good to me, but what's with the rounding?

**Comment by sdtaylor** [comment]
the sum of weights should be 1, but somehow the very small numbers are not adding up to 1 in the background. It's similar to this

```
> x = 1.1e-15 
> 1-x 
[1] 1 
> (1-x) == 1 
[1] FALSE
```

**Comment by sdtaylor** [comment]
here is a better example of exactly whats going on

```
> aic_values = c(10,50,100)
> delta_aic = aic_values - min(aic_values)
> weights = exp(-0.5 * delta_aic) / sum(exp(-0.5*delta_aic))
> sum(weights) == 1
[1] FALSE
> round(sum(weights), 10) == 1
[1] TRUE
```

**Comment by davharris** [comment]
If the concern is about the test, try all.equal() It allows for some imprecision/rounding error. By default, I think it only complains when the number is off by about ten billionths. 

That would let us still have the test, without needing to lose additional precision beyond the error introduced by floating point. 

Dave

**Comment by davharris** [comment]
Unless I'm too sick to read properly and you're just rounding for purposes of the test (i.e. you're using full precision in the output). In that case, just go ahead and merge.

Dave

**Comment by sdtaylor** [comment]
That's correct, it's just for the test. I made it a bit clearer.

**Comment by ethanwhite** [comment]
Thanks to both of you for this. Looks great!

@gmyenni - it would be good to rerun the forecasts for this weekend now that this is in so that we have the best possible prediction intervals for this months forecasts.

**Pull request merged**
