### PR TITLE
Add abstract and keywords

### PR DESCRIPTION
**Pull request by ethanwhite**

### CODE REVIEW

**Comment by ethanwhite** [comment]
All of the authors besides @skmorgane & I should take a look at this and either sign off on it or recommend changes.

**Review by bleds22e — COMMENTED** [review]
* need a comma after most up-to-date data in the 2nd sentence of the first point
* in 2nd point, 1st sentence, using near-term a second time seems a little odd--maybe "repeated forecasts a few time-steps in the future"? Not necessary to change, though.
* 2nd point, 2nd sentence, that dash should be a comma (or could be an emdash aka 3 dashes, but I prefer a comma here)
* 3rd point: I kind of like the idea of putting the last sentence first? But fine as is

Content looks great!

**Comment by ethanwhite** [comment]
Thanks @bleds22e - Your first and third points done as requested. For your second point I tried being more explicit "involves repeated daily to annual scale forecasts".  I decided to leave the interdisciplinary sentence where it was.

**Comment by gmyenni** [comment]
When listing the stages at the end of the second paragraph, it seems like it should be 'presentation' rather than 'presenting,' to match the rest of the ms and figure.

**Comment by ethanwhite** [comment]
Thanks @gmyenni - done.

**Comment by sdtaylor** [comment]
LGTM

**Comment by skmorgane** [comment]
Closes issue #201

**Pull request merged**
