### PR TITLE
Add website pages

### PR DESCRIPTION
**Pull request by sdtaylor**
for #82

### CODE REVIEW

**Comment by ethanwhite** [comment]
Getting the CI up and running introduced some conflicts in `docs/index.html`. Can you remove the rendered versions of the files and rebase and then we can let the CI generate the updated docs directory. Thanks.

**Comment by sdtaylor** [comment]
K, removed all the rendered files, did a rebase with the latest master and pushed back here, hopefully that works.

**Comment by ethanwhite** [comment]
Looks like the current build of the site is failing with the error:

```
Error in regexpr("\\.([[:alnum:]]+)$", x) : 
  argument "input" is missing, with no default
Calls: <Anonymous> -> %in% -> tolower -> <Anonymous> -> regexpr
```

It looks like this is from the use of `render()` without arguments. Should that be `render_site()`?

**Comment by sdtaylor** [comment]
Yep, thats it. Trying again.

**Pull request merged**
