### PR TITLE
Write forecast and AIC files to the predictions folder

### PR DESCRIPTION
**Pull request by ethanwhite**
All other code expects these in the predictions folder, but they were
currently being written to root.

### CODE REVIEW

**Comment by ethanwhite** [comment]
This is definitely true for most of the code but I'd like @gmyenni & @sdtaylor to take a look in case I'm forgetting something that is expecting these files to occur in the root directory for the repo.

**Comment by gmyenni** [comment]
Nope, as far as I know, they should go in the predictions folder.

**Comment by sdtaylor** [comment]
Same here, everything should go in predictions.

**Review by sdtaylor — APPROVED** [review]
Working for me

**Pull request merged**
